### ISSUE TITLE
p5.play seems to be loaded twice in mini/index.html

### ISSUE THREAD

**Issue by toolness** [joancc/ace_minicourse#40]
Hey @joancc, I was just looking at `mini/index.html` and noticed that p5.play seems to be loaded twice--once from `libs/p5.play.js`, and then again from some elastic beanstalk place. Is it ok if I remove one of them?

**Comment by toolness** [comment]
Ack! I'm actually finding that the double-loading of p5.play is **doubling the effects** of some of our game code, in particular the physics behaviors--when I remove either of the  scripts to p5.play, the character in level 0 jumps half as high, and is unable to win the level. :disappointed: 

So before removing one of them, we need to make sure the minicourse still works with only one loading of p5.play.

**Comment by joancc** [comment]
Hey @toolness , removed the duplicate play and fixed some levels with moving platforms and jumps. The elastic beanstalk files are coming from my aws account. The p5 play rebind is used to call an IIFE in p5 play. Because the p5 instance gets removed every time we hit run, we need that function to run again so play stuff can be initialized.
